services:
  web:
    image: php:8.4-apache # O use php:8.3-apache si 8.4 no está disponible
    container_name: php-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - app_network
    depends_on:
      - db
      - mailpit

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/app
    networks:
      - app_network
    working_dir: /app

  db:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_TCP_PORT: "${DB_PORT}"
      # --------------------------------------------------------------------
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "${FORWARD_PHPMYADMIN_PORT:-8008}:80"
    environment:
      PMA_HOST: "${DB_HOST}"
      # --------------------------------------------------------------------
      PMA_PORT: "${DB_PORT}"
    networks:
      - app_network
    depends_on:
      - "${DB_HOST}"

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
